# Generated by Django 4.1.4 on 2022-12-23 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='max_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
